# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - gocritic
    - gofmt
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    shadow: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  misspell:
    locale: US

issues:
  exclude-dirs:
    - vendor
  max-issues-per-linter: 50
  max-same-issues: 10
